'\" t
.\"         Title: yjl-sysusers.json
.\"        Author: Michael A. Peters
.\" Generator: Hand-coded
.\"      Date: 2023-05-26
.\"    Manual: File Formats
.\"  Language: English
.\"
.TH "YJL\-SYSUSERS\&.JSON" "5" "May 2023" "yjl\-sysusers\&.json 0\&.1\&.0" "File Formats"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH NAME
yjl\-sysusers\&.json \- static system user UID/GID database
.SH DESCRIPTION
The
\fByjl\-sysusers\&.json\fR file is a JSON dictionary of system user
and group names which have desired static assignment of User ID (UID)
and Group ID (GID)\&.
.PP
JSON (JavaScript Object Notation) was chosen because of both its ease
of use with Python and its ubiquity with programming languages in
general\&.
.PP
The \fByjl\-sysusers\&.json\fR file is used by the
\fByjl\-sysusers (8)\fR
wrapper to
\fBuseradd (8)\fR and
\fBgroupadd (8)\fR
system administration utilities\&.
.PP
In addition to static UID and GID assignments,
\fByjl\-sysusers\&.json\fR also has optional default options to pass
to the
\fBuseradd (8)\fR
command when creating the specified system user account\&.
.PP
Additionally, the
\fByjl\-sysusers\&.json\fR
file may have an entry titled
\fB00\-CONFIG\fR
that configures how the
\fByjl\-sysusers (8)\fR
utility handles dynamically assigned system UID and GID numbers\&.
.PP
.\" ---
.\" --- end description
.SH FILE LOCATION
.PP
Ordinarily this file should be installed as:
.sp
.RS 8
\fB/var/lib/yjl\-sysusers/yjl\-sysusers\&.json\fR
.RE
.PP
The file is a configuration file but it is also a read-only database
and once installed it should not be modified except by re-installation
of the package that provides it.
.PP
.\" ---
.\" --- end file location
.SH ACCOUNT NAME OBJECTS
.PP
Each system user and/or group account for which a static ID is desired
should have an \fBACCOUNT NAME OBJECT\fR using the \fBACCOUNT NAME\fR
as the index for the object\&.
.PP
The following case sensitive properties of an \fBACCOUNT NAME\fR describe
the \fBACCOUNT\fR:
.PP
\fImyid\fR
.RS 4
Integer\&. Required\&.
.sp
This property is the static UID/GID that should be used, if not already
in use, when creating a user and/or group of the \fBACCOUNT NAME\fR\&.
.sp
The \fBnobody\fR and \fBnogroup\fR entries may share the same \fImyid\fR
values but all other \fBACCOUNT NAME OBJECTS\fR must have a unique
\fImyid\fR value\&.
.sp
The \fBnobody\fR and \fBnogroup\fR entries may have a \fImyid\fR value
of \fI65534\fR but all other \fBACCOUNT NAME OBJECTS\fR must have a
value below \fI1000\fR\&.
.sp
The \fBroot\fR entry must have a \fImyid\fR value of \fI0\fR\&.
.sp
The \fImyid\fB property should not be within the dynamically assigned
system user range identified
by \fISYS_UID_MIN\fR and \fISYS_UID_MAX\fR in the GNU/Linux distribution
default
\fB/etc/login\&.defs\fR configuration file\&.
.RE
.PP
\fIusr\fR
.RS 4
Boolean\&. Recommended\&. Default value is \fIfalse\fR\&.
.sp
This property defines whether the default action of
\fByjl-sysusers (8)\fR
should be to create a user account associated with the
\fBACCOUNT NAME OBJECT\fR\&.
.sp
If the \fIusr\fR property is either not defined or defined to
\fIfalse\fR\ then the \fIgpr\fR property must be defined to
\fItrue\fR\&.
.RE
.PP
\fIgrp\fR
.RS 4
Boolean\&. Recommended\&. Default value is \fIfalse\fR\&.
.sp
This property defines whether the default action of
\fByjl-sysusers (8)\fR
should be to create a group account associated with the
\fBACCOUNT NAME OBJECT\fR\&.
.sp
If the \fIgrp\fR property is either not defined or defined to
\fIfalse\fR\ then the \fIusr\fR property must be defined to
\fItrue\fR\&.
.RE
.PP
\fIgroup\fR
.RS 4
String\&. Optional, rarely appropriate\&.
.sp
When present, this property defines the primary group that
a user of the same name as the \fBACCOUNT NAME OBJECT\fR
should belong to when a group of the same name is not to
br created\&.
.sp
When the \fIgroup\fR property is present, the \fIusr\fR
property must be defined as \fItrue\fR and the \fIgrp\fR
property should either not be defined or defined as
\fIfalse\fR\&.
.sp
When the \fIgroup\fR property is present, the string value
should match the name of another \fBACCOUNT NAME OBJECT\fR
that has a \fIgrp\fR property of \fItrue\fR\&.
.RE
.PP
\fIcomment\fR
.RS 4
String\&. Optional, recommended\&.
.sp
When present, this property defines the default ASCII English
version of the \fICOMMENT\fR
(also called \fIGECOS\fR) field of the /etc/passwd file (see
\fBman 5 passwd\fR) when
\fByjl-sysusers (8)\fR creates a user account using the name
\fBACCOUNT NAME\fR\&.
.sp
When the \fIcomment\fR property is not defined,
\fByjl-sysusers (8)\fR will default to using
"\fBACCOUNT NAME\fR system user account"
as the \fICOMMENT\fR when it creates a user account using the
name \fBACCOUNT NAME\fR\&.
.sp
The \fIcomment\fR property must be printable ASCII of no more
than 60 characters in length and must contain a colon or a
back\-slash\&.
.sp
When translations are available,
\fByjl-sysusers (8)\fR
will use translations of this property as provided by GNU
gettext for systems that uses a non-English default
language\&.
.RE
.PP
\fIhomedir\fR
.RS 4
String\&. Optional\&. Defaults to /dev/null\&.
.sp
When present, this property defines the default
\fIdirectory\fR field of the /etc/passwd file (see
\fBman 5 passwd\fR) when
\fByjl-sysusers (8)\fR creates a user account using the
name \fBACCOUNT NAME\fR\&.
.sp
This is usually called the "home directory" because
it defines the \fIHOME\fR environment variable for the
user account\&.
.sp
The \fByjl-sysusers (8)\fR utility enforces stricter rules
for system accounts, only allowing \fIhomedir\fR values
that are lower case alpha-numeric plus underscore,
forward-slash, and hyphen dashes\&.
.RE
.PP
\fIshell\fR
.RS 4
String\&. Optional, rarely appropriate\&.
.PP
When present, this property defines the default
\fIshell\fR field of the /etc/passwd file (see
\fBman 5 passwd\fR) when
\fByjl-sysusers (8)\fR creates a user account using the
name \fBACCOUNT NAME\fR\&.
.sp
The only valid values for the \fIshell\fR property of a
\fBACCOUNT NAME OBJECT\fR in the
\fByjl-sysusers\&.conf\fR file are
\fI/bin/bash\fR and \fI/bin/sh\fR\&.
.sp
Additional values may be specified to the
\fByjl-sysusers (8)\fR utility as long as the specified shell
is in /etc/shells (see
\fBman 5 shells\fR)\&.
.sp
When the \fBACCOUNT NAME OBJECT\fR does not have a \fIshell\fR
property and a valid \fISHELL\fR option is not passed to the
\fByjl-sysusers (8)\fR utility, the \fByjl-sysusers (8)\fR utility
will use \fB/sbin/nologin\fR (if it exists on the system) or
\fB/bin/false\fR for the \fIshell\fR field of the /etc/passwd file
when it creates a user account of \fBACCOUNT NAME\fR\&.
.RE
.PP
\fImkdir\fR
.RS 4
Boolean\&. Optional, defaults to \fIfalse\fR\&.
.RE
.PP

.\" ---
.\" --- end stuff
.SH COPYLEFT
.PP
\fByjl\-sysusers (8)\fR is
Copyright (c) 2023 YellowJacket GNU/Linux\&.
.sp
.RS 4
License SPDX:MIT <https://spdx.org/licenses/MIT.html>\&.
.sp
\fByjl\-sysusers\fR is
free software: you are free to change and redistribute it\&.
There is no WARRANTY, to the extent permitted by law\&.
.RE
.PP
This man page is
Copyright (c) 2023 YellowJacket GNU/Linux\&.
.sp
.RS 4
License SPDX:GFDL\-1\&.3\-or\-later
.br
<https://spdx\&.org/licenses/GFDL-1\&.3-or-later\&.html>\&.
.sp
Accuracy of this man page is stroven for but explicitly not
guaranteed\&.
.RE
.PP
.\" ---
.\" --- end copyleft
.SH AUTHORS
Michael A\&. Peters
.br
.RS 8
<anymouseprophet@gmail\&.com>
.RE
.PP
