'\" t
.\"     Title: yjl-sysusers
.\"    Author: Michael A. Peters
.\" Generator: Hand-coded
.\"   Created: 2023-05-26
.\"  Modified: 2023-06-01
.\"    Manual: System Management Commands
.\"  Language: English
.\"
.TH "YJL\-SYSUSERS" "8" "June 2023" "yjl\-sysusers 0\&.1\&.5" "System Management Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH NAME
yjl\-sysusers \- Add system users and groups
.SH SYNOPSIS
.HP \w'\fByjl-sysusers\fR\ 'u
\fByjl\-sysusers\fR [\fIOPTIONS\fR] \fIaccount\fR
.\" ---
.PP
.\" --- end Synopsis
.SH DESCRIPTION
\fByjl\-sysusers\fR
is a wrapper script to the operating system
\fBgroupadd (8)\fR
and
\fBuseradd (8)\fR
commands that allows respecting the operating system static
UID and GID assignment when available, without the need to
assign them manually\&.
.PP
Static UID and GID values, as well as some other parameters
useful to the
\fBuseradd (8)\fR
command, are defined in the file
\fByjl\-sysusers\&.json (5)\fR
which is normally located in the directory
/usr/share/yjl\-sysusers\&.
.PP
\fByjl\-sysusers\fR
was developed with RPM package scriptlets in mind\&.
.\" ---
.PP
.\" --- end Description
.SH OPTIONS
Options can be used when
\fIaccount\fR
has not been described in the
\fByjl\-sysusers\&.json (5)\fR
file or to override default
settings for
\fIaccount\fR
as defined in the
\fByjl\-sysusers\&.json (5)\fR
file\&.
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Display help message and exit\&.
.RE
.PP
\fB\-v\fR, \fB\-\-version\fR
.RS 4
Display version information and exit\&.
.RE
.PP
\fB\-\-bootstrap\fR
.RS 4
Validate the
\fByjl\-sysusers\&.json (5)\fR
file and if valid, dump the JSON to screen\&.
.sp
The
\fB\-\-bootstrap\fR
option is intended to be used during installation and packaging\&.
.RE
.PP
\fB\-c\fR, \fB\-\-comment\fR \&\fICOMMENT\fR
.RS 4
Define the comment field to be used in the /etc/passwd file\&.
This is used to provide a brief description of
\fIaccount\fR\&.
\fICOMMENT\fR
must be printable ASCII, excluding the \\ and : characters\&.
\fICOMMENT\fR
must not exceed 120 characters\&.
.RE
.PP
\fB\-d\fR, \fB\-\-home\fR \fIHOME\fR
.RS 4
Define the home directory to be used with the system user account\&.
It must be full path and can only use lower\-case alpha\-numeric
characters plus underscore, forward\-slash, and hyphen\&.
.RE
.PP
\fB\-s\fR, \fB\-\-shell\fR \fISHELL\fR
.RS 4
Define the login shell to be used with the system user account\&.
If
\fISHELL\fR
is not present in /etc/shells or is not installed on the
system, then /sbin/nologin or /bin/false will be substituted\&.
.sp
Any argument that is not full-path is invalid, so you can
just use
\fInoshell\fR
as the
\fISHELL\fR
arguement to guarantee that either /sbin/nologin or /bin/false
are used as the login shell.
.sp
\fByjl\-sysusers\fR will use /sbin/nologin for any
\fIaccount\fR
that does not have a valid
\fISHELL\fR
specified unless /sbin/nologin is not present on the system\&.
In such cases, /bin/false is used instead\&.
.RE
.PP
\fB\-g\fR, \fB\-\-group\fR \fIGROUP\fR
.RS 4
Define the primary group for the user
\fIaccount\fR
with a different group name than
\fIaccount\fR\&.
.sp
If the group
\fIGROUP\fR
does not exist, it will be created automatically\&.
.RE
.PP
\fB\-\-onlyuser\fR
.RS 4
Boolean flag. When this flag is specified, only the user
\fIaccount\fR
will be created\&. If a valid primary group is not specified
with the
\fB\-g\fR, \fB\-\-group\fR \fIGROUP\fR
option and a group of
\fIaccount\fR
name does not already exist, then the user will be put in the
"nogroup" equivalent. See
\fByjl\-sysusers\&.json (5)\fR\&.
.RE
.PP
\fB\-\-onlygroup\fR
.RS 4
Boolean flag. When this flag is specified, only the group
\fIaccount\fR
will be created\&.
.RE
.PP
\fB\-\-userandgroup\fR
.RS 4
Boolean flag. When this flag is specified, both a user and
group
\fIaccount\fR
will be created\&. This is actually the default behavior but the
\fByjl\-sysusers\&.json (5)\fR
file might be configured to only create one or the other for the
specified
\fIaccount\fR
name\&.
.RE
.PP
\fB\-\-mkdir\fR
.RS 4
Boolean flag. When this flag is specified, the
\fIHOME\fR
directory for
\fIaccount\fR
will be created by
\fBuseradd (8)\fR
if it does not already exist\&.
.sp
The default with system accounts us not to create the
\fIHOME\fR
directory automatically because that often copies the contents
of /etc/skel into the
\fIHOME\fR
directory, which is rarely desired for system accounts\&. 
.RE
.PP
\fB\-\-delete\fR
.RS 4
As of version 0\&.1\&.5 this is not yet implemented\&.
.sp
This flag is used to specify that any user and group of
the name
\fIaccount\fR
should be deleted\&. It does does not delete any files
owned by the user or group
\fIaccount\fR\&.
.RE
.\" ---
.PP
.\" --- end Options
.SH USAGE NOTES
Python 3 is needed for
\fByjl\-sysusers\fR\&.
Testing has been done with the CentOS 7 packaged
Python 3\&.6\&.4 (released 2017 December 19) and with vanilla
Python 3\&.11\&.3 (released 2023 April 05)\&.
.sp
.\" ---
.PP
.\" --- end Usage Notes
.SH PACKAGER NOTES
When creating an RPM (or other) package that has files owned by
non-root users and groups, you should use
\fByjl\-sysusers\fR
in the package
\fI%pre\fR
scriptlet to ensure the appropriate users and groups exist at the
time the files are installed\&.
.sp
RPM packagers should use the macro
\fB%{_yjl_sysusers}\fR
rather than the command
\fByjl\-sysusers\fR
or
\fB/usr/sbin/yjl\-sysusers\fR\&.
.sp
RPM pacjagers should
\fBBuildRequires: yjl\-sysusers\fR\&.
.sp
RPM packagers should
\fBRequires(pre): %{_yjl_sysusers}\fR\&.
.sp
Packagers should avoid using
\fB\-c\fR, \fB\-\-comment\fR \fICOMMENT\fR
as it can interfere with the string being properly translated
via gettext i18n facilities into the preferred language of the
end user system\&.
.sp
Packagers should usually avoid using
\fB\-\-mkdir\fR\&.
.sp
When
\fBuseradd (8)\fR
creates the
\fIHOME\fR
directory, it also copies the contents of /etc/skel into that
directory\&. Usually that is not desired\&. It is often better
to have the RPM package create and own the
\fIhome\fR
directory when a home directory is needed\&.
.sp
Packagers should never assume the contents of the
\fByjl-sysusers\&.json (5)\fR
file are correct for the package, but should specify the correct
option parameters when ensuring that
\fIaccount\fR
exists\&.
.sp
The primary motivation for this wrapper script is to allow for
truly portable RPM spec files that can build and install on many
GNU/Linux distributions while still respecting the static GID/UID
assignments for system users and groups that a distribution (or
system administrator) wants to enforce\&.
.sp
A secondary motive for this wrapper script is to allow for the
internationalization of system user account descriptions (the
\fICOMMENT\fR
field of /etc/passwd) at the time of package install\&.
.sp
Lazy packaging where the packager relies upon
\fByjl-sysusers\&.json (5)\fR
to have correct user account parameters is not a motive for this
package, although compensating for lazy packaging was a motive for
allowing sane
\fBuseradd (8)\fR
defaults to be specified in that file\&.
.\" ---
.PP
.\" --- end Packager Notes
.SH CONFIGURATION
The default options on a
per-\fIaccount\fR
basis for accounts with preferred static UID/GID assignment are
in the
\fByjl-sysconfig\&.json (5)\fR
file\&. Most options except for the UID/GID, protection from deletion,
and positive creation of the
\fIHOME\fR
directory can be overriden with options passed to
\fByjl\-sysusers\fR\&.
.\" ---
.PP
.\" --- end configuration
.SH FILES
/usr/sbin/yjl\-sysusers
.RS 4
The Python 3 wrapper to
\fBgroupadd (8)\fR
and
\fBuseradd (8)\fR\&.
This man page describes use of that Python wrapper.
.RE
.PP
/usr/share/yjl\-sysusers/yjl\-sysusers\&.json
.RS 4
The JSON database on a
per-\fIaccount\fR
basis for preferred static UID/GID and default options to
pass to
\fBuseradd (8)\fR\&.
.RE
.PP
/usr/lib/rpm/macros.d/macros\&.yjl\-sysusers
.RS 4
The definition of the
\fB%{_yjl_sysusers}\fR
macro that is used with
\fBrpmbuild (8)\fR
to create RPM packages that utilize
\fByjl\-sysusers\fR\&.
.RE
.\" ---
.PP
.\" --- end files
.SH EXAMPLES
\fByjl-sysusers\fR
\fB\-\-onlygroup\fR
\fIplocate\fR
.sp
.RS 4
Ensure the
\fIplocate\fR
group exists, without creating a
\fIplocate\fR
user\&.
.RE
.PP
\fByjl-sysusers\fR
\fB\-g\fR \fImail\fR
\fB\-h\fR \fI/var/lib/sendmail\fR
\fB\-s\fR \fInoshell\fR
\fIsendmail\fR
.sp
.RS 4
Ensure the
\fImail\fR
group exists\&. Ensure the
\fIsendmail\fR
user exists, creating it if necessary using
\fI/var/lib/sendmail\fR
as the
\fIHOME\fR
directory, and using either /sbin/nologin or /bin/false as
the login shell\&.
.sp
If the
\fIsendmail\fR
user does not already exist, it will be created
with
\fImail\fR
as the primary group it belongs to.
.RE
.PP
\fByjl-sysusers\fR
\fB\-\-onlygroup\fR
\fImail\fR && \\
.br
\fByjl-sysusers\fR
\fB\-\-userandgroup\fR \\
.br
.RS 2
\fB\-h\fR \fI/var/lib/sendmail\fR
\fB\-s\fR \fInoshell\fR
\fIsendmail\fR && \\
.RE
.br
\fBusermod\fR \fB\-a\fR
\fB\-G\fR \fImail\fR
\fIsendmail\fR
.sp
.RS 4
First ensure that the
\fImail\fR
group exists\&. Then ensure that the
\fIsendmail\fR
user exists as in the previous example, only if the user is
created, it is created with
\fIsendmail\fR
as the primary group\&. Finally, add the
\fIsendmail\fR
user to the
\fImail\fR
group\&.
.sp
As a packager, btw, that is my preferred method of dealing with
system users that need to belong to a system group of a different
name.
.RE
.\" ---
.PP
.\" --- end Examples
.SH EXIT STATUS
.PP
\fI0\fR
.RS 4
success
.RE
.PP
\fI1\fR
.RS 4
The program failed to create requested group and/or user\&.
.RE
.\" ---
.PP
.\" --- end exit status
.SH TODO
.PP
Implement GNU gettext i18n and get some translations\&. Fix the bugs
listed below\&.
.\" ---
.PP
.\" --- end todo
.SH BUGS
There quite likely are some\&.
.\" ---
.PP
.\" --- end bugs
.SH SEE ALSO
\fByjl-sysusers\&.json(5)\fR,
\fBpasswd(5)\fR,
\fBgroup(5)\fR,
\fBlogin\&.defs(5)\fR,
\fBshells(5)\fR,
\fBgroupadd(8)\fR,
\fBuseradd(8)\fR,
\fBusermod(8)\fR,
\fBrpmbuild(8)\fR
.\" ---
.PP
.\" --- end see also
.SH COPYLEFT
The
\fByjl\-sysusers\fR
utility is Copyright (c) 2023 YellowJacket GNU/Linux\&.
.sp
.RS 4
License: SPDX:MIT <https://spdx\&.org/licenses/MIT\&.html>\&.
.sp
\fByjl\-sysusers\fR is
free software: you are free to change and redistribute it\&.
There is no WARRANTY, to the extent permitted by law\&.
.RE
.PP
This man page is Copyright (c) 2023 YellowJacket GNU/Linux\&.
.sp
.RS 4
License: SPDX:GFDL\-1\&.3\-or\-later
.br
<https://spdx\&.org/licenses/GFDL-1\&.3-or-later\&.html>\&.
.sp
Accuracy of this man page is stroven for but explicitly is not
guaranteed\&.
.RE
.\" ---
.PP
.\" --- end copyleft
.SH AUTHORS
Michael A\&. Peters
.br
.RS 8
<anymouseprophet@gmail\&.com>
.RE
.\" ---
.PP
.\" --- end authors
